
services:
  php:
    build:
      context: ./docker/php    
    container_name: php    
    volumes:
      - ./src:/var/www/html    
    depends_on:
      - db       
    networks:
      - sistema
    env_file:
      - .env
  
  node:
    build:
      context: ./docker/node
    container_name: node    
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html      
    depends_on:
      - php       
    ports:
      - "5173:5173"
    networks:
      - sistema

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php   
    networks:
      - sistema   
 
  db:
    image: mariadb:lts-ubi9
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"  
    networks:
      - sistema  

volumes:
  dbdata:  

networks:
  sistema:
    driver: bridge